sudo: required

language: c

services:
  - docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --tag $DOCKER_USERNAME/rnalien -f Dockerfile.dev .

script:
  - docker create --name develcontainer devel $DOCKER_USERNAME/rnalien
  - docker images
  - mkdir RNAlien
  - docker cp develcontainer:/RNAlien RNAlien
  - docker cp develcontainer:/RNAlienStatistics RNAlien
  - docker cp develcontainer:/cmsearchToBed RNAlien
  - docker cp develcontainer:/RNAcentralHTTPRequest RNAlien
  - docker cp develcontainer:/RNAlienScan RNAlien
  - cp LICENSE RNAlien
  - tar -cvzf RNAlien.tar.gz RNAlien
  - docker push $DOCKER_USERNAME/rnalien
  - docker run --rm $DOCKER_USERNAME/rnalien /RNAlien --help


deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: "RNAlien.tar.gz"
  on:
    tags: true
